apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: roboshop
spec:
  type: {{ .Values.Service.typename }}
  selector:
    project: helm-demo
    purpose: load-balancer
  ports:
  - protocol: TCP
    port: {{ .Values.Service.portno }}  #service port
    targetPort: 80  #container port
    nodePort: 30007
